### ISSUE TITLE
unable to build library after upgrade to gradle 7.2 and AGP 7.0.2

### ISSUE THREAD

**Issue by igagis** [howardpang/androidNativeBundle#14]
After upgrading my project to `gradle` `7.2` and AGP `7.0.2` I started getting the following build error:

```
Execution failed for task ':r4:bundleStaticLibPrepareRelease'.
> No such property: externalNativeJsonGenerator for class: com.android.build.gradle.internal.scope.MutableTaskContainer
```

Please see the relevant build log here:
https://github.com/cppfw/r4/runs/3651546091?check_suite_focus=true#step:6:127

Is this a problem in `androidNativeBundle` plugin?

**Comment by howardpang** [comment]
Gradle 7.2 is not support yet, i will take tome time to support it , thanks

**Comment by igagis** [comment]
Ah, I see. What is the latest supported gradle version?

**Comment by howardpang** [comment]
android gradle plugin 3.0.0 - 4.1.0

**Comment by howardpang** [comment]
Please try 1.1.0

**Comment by igagis** [comment]
I'll try as soon as I can. Thanks for the fix!

**Comment by igagis** [comment]
Ok, it seems working for me. Thanks again for great plugin!
