### ISSUE TITLE
Issue related with flavorDimensions

### ISSUE THREAD

**Issue by IlyaPavlik** [howardpang/androidNativeBundle#15]
If the project has several flavorDimensions the project won't be built.

Example:
```
apply plugin: 'com.ydq.android.gradle.native-aar.import'

flavorDimensions 'type1', 'type2'

productFlavors {
    flavor1 {
        dimension 'type1'
    }
    flavor2 {
        dimension 'type1'
    }
    flavor3 {
        dimension 'type2'
    }
    flavor4 {
        dimension 'type2'
    }
}
```

Cause of the issue might be combined flavor names and this name is used for finding product flavor for a variable (`gradleMk `).

https://github.com/howardpang/androidNativeBundle/blob/f8c2fcf68ed6db8b32bd018342df7061ee059606/buildSrc/src/main/groovy/com/yy/android/gradle/nativedepend/NativeBundleImportPlugin.groovy#L110

**Comment by howardpang** [comment]
Please try 1.1.0

**Comment by IlyaPavlik** [comment]
Unfortunatelly the new version doesn't work for me.
Build failed:

```
java.lang.NullPointerException: Cannot get property 'configurationModel' on null object
Caused by: java.lang.NullPointerException: Cannot get property 'configurationModel' on null object
	at com.yy.android.gradle.nativedepend.GradleApiAdapter.addArgumentToNativeBuildOption(GradleApiAdapter.groovy:98)
	at com.yy.android.gradle.nativedepend.GradleApiAdapter$addArgumentToNativeBuildOption.call(Unknown Source)
	at com.yy.android.gradle.nativedepend.NativeBundleImportPlugin$_apply_closure1.doCall(NativeBundleImportPlugin.groovy:79)
```

**Comment by howardpang** [comment]
What's your environment

**Comment by IlyaPavlik** [comment]
I've updated the gradle plugin, so now it's 7.0.3

**Comment by howardpang** [comment]
My demo is OK(https://github.com/howardpang/nativeBundleDemo);Can you show your build.gradle.

**Comment by IlyaPavlik** [comment]
Thanks for demo. I've reproduced the issue with your demo.

To reproduce the issue you need use only 
`'com.ydq.android.gradle.native-aar.import'`
And remove/comment `externalNativeBuild` block in each flavor

Example: [build.txt](https://github.com/howardpang/androidNativeBundle/files/7626083/build.txt)

In my project I implemented `externalNativeBuild` in `defaultConfig` block

**Comment by howardpang** [comment]
Thanks, i have reproduced the issue, and will resolve it later

**Comment by howardpang** [comment]
Try 1.1.1

**Comment by IlyaPavlik** [comment]
It works now, thank you!
