### ISSUE TITLE
Unable to build library after upgrade to gradle 7.4，AGP 7.3.0 and Flutter 3.3.9

### ISSUE THREAD

**Issue by zincPower** [howardpang/androidNativeBundle#17]
After I upgrade my Flutter version to 3.3.9 , so I need upgrade Gradle to 7.4 and AGP to 7.3 ( AGP need 7.1.2 at least).

 I started getting the following build error:

```
* Where:
Initialization script '/Users/jiangpengyong/Documents/env/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 94

* What went wrong:
Cannot change dependencies of dependency configuration ':compileOnly' after it has been included in dependency resolution.
```

Is this the problem in this plugin? How can I solve this problem?

**Comment by howardpang** [comment]
The plugin is now only support AGP 3.0.0 - 7.0.3；So it take some time to support AGP 7.3;

**Comment by howardpang** [comment]
try 1.1.2

**Comment by howardpang** [comment]
Try 1.1.3
