### ISSUE TITLE
Error with latest Flutter Beta 3.27.0-0.1.pre

### ISSUE THREAD

**Issue by martinhaintz** [howardpang/androidNativeBundle#20]
Hello, 

The androidNativeBundle is integrated into the [Sentry Flutter example app](https://github.com/getsentry/sentry-dart/tree/main/flutter/example), which worked well until the `Flutter Beta 3.27.0-0.1.pre` was released.

This is the error:
```
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not resolve all dependencies for configuration ':app:releaseCompileClasspath'.
      > Could not find io.flutter:x86_release:1.0.0-af0f0d559c8a87d912a20971bbd84afc80a54b0f.
        Required by:
            project :app
```

It looks like this error is related to this Bundle. You can find a detailed explanation about this error here in [this issue](https://github.com/getsentry/sentry-dart/issues/2381)

Any ideas on how to fix this error? 

Thanks

**Comment by howardpang** [comment]
There maybe build enviroment problem, it succeed when I import your demo to android studio to build。also it failed when use commondline 'flutter build apk --debug' to build;Give me some time to fixed it.

**Comment by martinhaintz** [comment]
We also found out, that there was a change in the flutter gradle plugin. The maintainer of this PR [mentioned](https://github.com/flutter/flutter/pull/154476#discussion_r1827957100), that maybe we have an error in our config. But as you also facing this issue, I am not sure anymore.

Thanks in advance for your help.

**Comment by romtsn** [comment]
@howardpang as mentioned in https://github.com/flutter/flutter/pull/154476#discussion_r1830494433 you'd probably have to change how the plugin works - e.g. create a task (for generating .mk files) that receives configuration as lazy input instead of eagerly resolving configuration at the configuration phase.

**Comment by howardpang** [comment]
@martinhaintz Try 1.1.5

**Comment by martinhaintz** [comment]
@howardpang thank you very much for your quick fix. with `1.1.5` it works again.
