### ISSUE TITLE
Need to be ableto give filter for header files

### ISSUE THREAD

**Issue by igagis** [howardpang/androidNativeBundle#4]
Recently there was a pull request which made the plugin only to include `.h` files to generated `AAR` package. This is good, but not flexible.

Need to add possibility to set an option in gradle file like `includeHeaderFiles` which can be set to something like `['*.h', '*.hpp', '*.hxx']`. Then the plugin will only add header files which satisfy the given filter.

**Comment by howardpang** [comment]
New version 1.0.5 will include all files in `headerDir`, if you want you exclude some files set `excludeHeaderFiles` option, read README for detail

@paulo-raca FYI

**Comment by igagis** [comment]
I see your approach, but it still has problems this way. Sometimes there are not only `.cpp` files stored along with headers, but also other files line `makefiles` or build artifacts from non-android build, etc.
It would be better to have option `includeFilter.add(**/*.hxx)` and only include files which satisfy the filter. But, if filter is not set, then include all files. Is it possible to do it that way?

**Comment by igagis** [comment]
By the way, readme file has `excludeHeaderFiles.add("**/**.cpp")`. Is it `**/**.cpp` or should it be `**/*.cpp`, is it a typo?

**Comment by howardpang** [comment]
> By the way, readme file has `excludeHeaderFiles.add("**/**.cpp")`. Is it `**/**.cpp` or should it be `**/*.cpp`, is it a typo?

the two way is also correct

**Comment by howardpang** [comment]
I have add `includeHeaderFilter` option as you suggest in new version 1.0.6

**Comment by igagis** [comment]
It works well now! Thank you for the quick fix!
