### ISSUE TITLE
Add option to pack static libs to the same AAR

### ISSUE THREAD

**Issue by igagis** [howardpang/androidNativeBundle#5]
Currently there is a `bundleStatic = true` option which packs static libs to a separate AAR package.

Need to add another option `separateStaticAAR = false` to indicate that the static libs must be added to the same main AAR package.

**Comment by howardpang** [comment]
There are some consideration for putting static libs to another AAR;First is that the user didn't know whether their link static lib or shared lib; The most import is that if put static lib and shared lib to the same AAR, if the user use static lib, the app will packet the shared lib to apk which is not necessary and it will increase apk size

**Comment by igagis** [comment]
ok, I haven't thought about that, it makes sense. Closing the issue. Thanks!
