### ISSUE TITLE
Publish lib to Maven central

### ISSUE THREAD

**Issue by marandaneto** [howardpang/androidNativeBundle#8]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by howardpang** [comment]
Got it, i will publish it to maven recently :)

**Comment by marandaneto** [comment]
let me know if you need help, an easy win is to use this plugin: https://github.com/vanniktech/gradle-maven-publish-plugin
the other solution would be to publish to Gradle Plugin Portal https://plugins.gradle.org/docs/publish-plugin

thanks again for the plugin :)

**Comment by howardpang** [comment]
I have publish to maven central, because i have not 'ydq.com' domain, so i shoud change the group and artifact id to "io.github.howardpang:androidNativeBundle".

**Comment by marandaneto** [comment]
this can be closed now, thanks https://search.maven.org/artifact/io.github.howardpang/androidNativeBundle
